loom.platform=fabric
archives_base_name=PepeLand Helper
minecraft_version=26.2
alinlib_minecraft_version=26.2
abi_minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.157.0+26.2
minecraft_dependency=>=26.2
modmenu_version=20.0.1
litematica=jzraAo7b
malilib=xKxhjDJ2
minedows=KVgBQwg0
pochatok=ToJ1ODal

modrinth_title = [26.2] 
modrinth_versions=26.2